export const ImageEnum = {
  FONTS: {},
  ICONS: {
    CLOSE: "/assets/icons/Close.svg",
    ARROW_DOWN_L_WHITE: "/assets/icons/arrow_Down_L_White.svg",
    ARROW_LEFT_L_GRAY: "/assets/icons/arrow_Left_L_Gray.svg",
    ARROW_RIGHT_L_BLACK: "/assets/icons/arrow_Right_L_Black.svg",
    ARROW_RIGHT_L_GRAY: "/assets/icons/arrow_Right_L_Gray.svg",
    ARROW_RIGHT_L_WHITE: "/assets/icons/arrow_Right_L_White.svg",
    ARROW_BACKWARD_IOS: "/assets/icons/arrow_backward_ios.svg",
    ARROW_FORWARD_IOS: "/assets/icons/arrow_forward_ios.svg",
    ARROW_LEFT_DEFAULT: "/assets/icons/arrow_left_default.svg",
    ARROW_LEFT_DISABLED: "/assets/icons/arrow_left_disabled.svg",
    ARROW_RIGHT_DEFAULT: "/assets/icons/arrow_right_default.svg",
    ARROW_RIGHT_DISABLED: "/assets/icons/arrow_right_disabled.svg",
    BLUEBADGEINFO: "/assets/icons/blueBadgeInfo.svg",
    BRONZERANKBADGE: "/assets/icons/bronzeRankBadge.svg",
    CHECKBOX_FILL: "/assets/icons/checkbox-fill.svg",
    CHECKBOX_UNFILL: "/assets/icons/checkbox-unfill.svg",
    CHEVRON_NEXT: "/assets/icons/chevron-next.svg",
    CHEVRON_PREV: "/assets/icons/chevron-prev.svg",
    CLOCK_WHITE: "/assets/icons/clock_white.svg",
    CLOSE_GRAY: "/assets/icons/close_gray.svg",
    COUPON_COFFEE: "/assets/icons/coupon_coffee.svg",
    DESIGNDETAIL: "/assets/icons/designDetail.svg",
    DOTLINE: "/assets/icons/dotLine.svg",
    EVENT_BADGE_BONUS: "/assets/icons/event_badge_bonus.svg",
    EVENT_BADGE_BONUS_DISABLED: "/assets/icons/event_badge_bonus_disabled.svg",
    EVENT_BADGE_NORMAL: "/assets/icons/event_badge_normal.svg",
    EVENT_BADGE_NORMAL_DISABLED:
      "/assets/icons/event_badge_normal_disabled.svg",
    GOLDRANKBADGE: "/assets/icons/goldRankBadge.svg",
    GREENBADGEINFO: "/assets/icons/greenBadgeInfo.svg",
    NORMALRANKBADGE: "/assets/icons/normalRankBadge.svg",
    PENCIL: "/assets/icons/pencil.svg",
    POPOVER: "/assets/icons/popover.svg",
    POPOVERBUTTON: "/assets/icons/popoverButton.svg",
    RETRYBUTTON: "/assets/icons/retryButton.svg",
    RETRY_DISABLED: "/assets/icons/retry_disabled.svg",
    SILVERRANKBADGE: "/assets/icons/silverRankBadge.svg",
    UPPERRIGHTBUTTON: "/assets/icons/upperRightButton.svg",
    URLBUTTON: "/assets/icons/urlButton.svg",
  },
  IMAGES: {
    DRAWING: {
      CELEBRATION: "/assets/images/drawing/celebration.gif",
      GUIDE_01: "/assets/images/drawing/guide_01.webp",
      GUIDE_02: "/assets/images/drawing/guide_02.webp",
      GUIDE_03: "/assets/images/drawing/guide_03.webp",
      GUIDE_04: "/assets/images/drawing/guide_04.webp",
      GUIDE_05: "/assets/images/drawing/guide_05.webp",
    },
    NEWCAR: {
      DESIGN_BANNER: "/assets/images/newCar/design_banner.webp",
      DRIVING_BANNER: "/assets/images/newCar/driving_banner.webp",
      EXTERIOR_BLACK: "/assets/images/newCar/exterior_black.webp",
      EXTERIOR_BLACKINK_BLACK:
        "/assets/images/newCar/exterior_blackInk_black.webp",
      EXTERIOR_BLACKINK_WHITEMATTE:
        "/assets/images/newCar/exterior_blackInk_whiteMatte.webp",
      EXTERIOR_BLACKINK_WHITEPEARL:
        "/assets/images/newCar/exterior_blackInk_whitePearl.webp",
      EXTERIOR_BLACK_COLOR: "/assets/images/newCar/exterior_black_color.webp",
      EXTERIOR_BLUE: "/assets/images/newCar/exterior_blue.webp",
      EXTERIOR_BLUE_COLOR: "/assets/images/newCar/exterior_blue_color.webp",
      EXTERIOR_BROWN: "/assets/images/newCar/exterior_brown.webp",
      EXTERIOR_BROWN_COLOR: "/assets/images/newCar/exterior_brown_color.webp",
      EXTERIOR_CYBER: "/assets/images/newCar/exterior_cyber.webp",
      EXTERIOR_CYBER_COLOR: "/assets/images/newCar/exterior_cyber_color.webp",
      EXTERIOR_FRONT_01: "/assets/images/newCar/exterior_front_01.webp",
      EXTERIOR_FRONT_02: "/assets/images/newCar/exterior_front_02.webp",
      EXTERIOR_FRONT_03_1: "/assets/images/newCar/exterior_front_03_1.webp",
      EXTERIOR_FRONT_03_2: "/assets/images/newCar/exterior_front_03_2.webp",
      EXTERIOR_FRONT_04_1: "/assets/images/newCar/exterior_front_04_1.webp",
      EXTERIOR_FRONT_04_2: "/assets/images/newCar/exterior_front_04_2.webp",
      EXTERIOR_FRONT_04_3: "/assets/images/newCar/exterior_front_04_3.webp",
      EXTERIOR_FRONT_04_4: "/assets/images/newCar/exterior_front_04_4.webp",
      EXTERIOR_FRONT_04_5: "/assets/images/newCar/exterior_front_04_5.webp",
      EXTERIOR_FRONT_BACKGROUND:
        "/assets/images/newCar/exterior_front_background.webp",
      EXTERIOR_GRAY: "/assets/images/newCar/exterior_gray.webp",
      EXTERIOR_GRAY_COLOR: "/assets/images/newCar/exterior_gray_color.webp",
      EXTERIOR_GREEN: "/assets/images/newCar/exterior_green.webp",
      EXTERIOR_GREEN_COLOR: "/assets/images/newCar/exterior_green_color.webp",
      EXTERIOR_ORANGE: "/assets/images/newCar/exterior_orange.webp",
      EXTERIOR_ORANGE_COLOR: "/assets/images/newCar/exterior_orange_color.webp",
      EXTERIOR_REAR_01: "/assets/images/newCar/exterior_rear_01.webp",
      EXTERIOR_REAR_02: "/assets/images/newCar/exterior_rear_02.webp",
      EXTERIOR_REAR_03_1: "/assets/images/newCar/exterior_rear_03_1.webp",
      EXTERIOR_REAR_03_2: "/assets/images/newCar/exterior_rear_03_2.webp",
      EXTERIOR_REAR_04: "/assets/images/newCar/exterior_rear_04.webp",
      EXTERIOR_REAR_05: "/assets/images/newCar/exterior_rear_05.webp",
      EXTERIOR_REAR_BACKGROUND:
        "/assets/images/newCar/exterior_rear_background.webp",
      EXTERIOR_WHITEMATTE_COLOR:
        "/assets/images/newCar/exterior_whiteMatte_color.webp",
      EXTERIOR_WHITEPEARL: "/assets/images/newCar/exterior_whitePearl.webp",
      EXTERIOR_WHITEPEARL_COLOR:
        "/assets/images/newCar/exterior_whitePearl_color.webp",
      GALLERY_EXTERIOR: "/assets/images/newCar/gallery_exterior.webp",
      GALLERY_INTERIOR: "/assets/images/newCar/gallery_interior.webp",
      HYBRID01: "/assets/images/newCar/hybrid01.webp",
      HYBRID02: "/assets/images/newCar/hybrid02.webp",
      HYBRID03: "/assets/images/newCar/hybrid03.webp",
      HYBRID04: "/assets/images/newCar/hybrid04.webp",
      INTERIOR_01: "/assets/images/newCar/interior_01.webp",
      INTERIOR_02: "/assets/images/newCar/interior_02.webp",
      INTERIOR_03: "/assets/images/newCar/interior_03.webp",
      INTERIOR_04: "/assets/images/newCar/interior_04.webp",
      INTERIOR_05: "/assets/images/newCar/interior_05.webp",
      INTERIOR_06: "/assets/images/newCar/interior_06.webp",
      INTERIOR_07: "/assets/images/newCar/interior_07.webp",
      INTERIOR_BACKGROUND: "/assets/images/newCar/interior_background.webp",
      INTERIOR_BEIGE: "/assets/images/newCar/interior_beige.webp",
      INTERIOR_BEIGE_COLOR: "/assets/images/newCar/interior_beige_color.webp",
      INTERIOR_BLACK: "/assets/images/newCar/interior_black.webp",
      INTERIOR_BLACKINK_COLOR:
        "/assets/images/newCar/interior_blackInk_color.webp",
      INTERIOR_BLACK_COLOR: "/assets/images/newCar/interior_black_color.webp",
      INTERIOR_BLACKINK: "/assets/images/newCar/interior_blackink.webp",
      INTERIOR_BROWN: "/assets/images/newCar/interior_brown.webp",
      INTERIOR_BROWN_COLOR: "/assets/images/newCar/interior_brown_color.webp",
      INTERIOR_EXCLUSIVE_FAKEBLACK:
        "/assets/images/newCar/interior_exclusive_fakeblack.webp",
      INTERIOR_FAKEBLACK_COLOR:
        "/assets/images/newCar/interior_fakeBlack_color.webp",
      INTERIOR_GRAY_COLOR: "/assets/images/newCar/interior_gray_color.webp",
      INTERIOR_PRESTIGE_BROWN:
        "/assets/images/newCar/interior_prestige_brown.webp",
      INTERIOR_PRESTIGE_FAKEBLACK:
        "/assets/images/newCar/interior_prestige_fakeblack.webp",
      INTERIOR_PRESTIGE_GRAY:
        "/assets/images/newCar/interior_prestige_gray.webp",
      INTERIOR_PRESTIGE_REALBLACK:
        "/assets/images/newCar/interior_prestige_realblack.webp",
      INTERIOR_REALBLACK_COLOR:
        "/assets/images/newCar/interior_realBlack_color.webp",
      NEWCAR_BANNER_BACKGROUND:
        "/assets/images/newCar/newcar_banner_background.webp",
      NEWCAR_BANNER_CAR: "/assets/images/newCar/newcar_banner_car.webp",
      PARTS1: "/assets/images/newCar/parts1.webp",
      PARTS2: "/assets/images/newCar/parts2.webp",
      PARTS3: "/assets/images/newCar/parts3.webp",
      PARTS4: "/assets/images/newCar/parts4.webp",
      SPACE_5: "/assets/images/newCar/space_5.webp",
      SPACE_6: "/assets/images/newCar/space_6.webp",
      SPACE_7: "/assets/images/newCar/space_7.webp",
      SPACE_BANNER: "/assets/images/newCar/space_banner.webp",
      TECH01: "/assets/images/newCar/tech01.webp",
      TECH02: "/assets/images/newCar/tech02.webp",
      TECH03: "/assets/images/newCar/tech03.webp",
      TECH04: "/assets/images/newCar/tech04.webp",
      TECH05: "/assets/images/newCar/tech05.webp",
      TECH06: "/assets/images/newCar/tech06.webp",
      TECH07: "/assets/images/newCar/tech07.webp",
    },
  },
  LOGOS: {
    HYUNDAI_MOTOR_COMPANY_LOGO_1:
      "/assets/logos/Hyundai_Motor_Company_logo_1.svg",
    HYUNDAILOGINBUTTON: "/assets/logos/hyundaiLoginButton.svg",
    HYUNDAI_LOGO: "/assets/logos/hyundai_logo.svg",
    NAVERLOGINBUTTON: "/assets/logos/naverLoginButton.svg",
  },
};
